### ISSUE TITLE
Fix ghost notes bug

### ISSUE THREAD

**Issue by rubiarg** [JRegimbal/crescendo#3]
When switching through measures, the forces of tangible elements are being accumulated without taking into consideration whether the element is visible or not. This creates a feeling of "ghost" notes on the right and left corners of the visible measure

https://user-images.githubusercontent.com/9599706/112430634-a651f100-8cfb-11eb-895e-052e9b655419.mov

```  
public PVector force(PVector posEE, PVector velEE) {
   PVector force = new PVector(0, 0);
   for (PShape line : lines) {
      force.set(force.add(staffForce(posEE, velEE, line)));
   }
   for (OrderedMusicElement element : elements) {
      // TODO only add visible elements
      if (element instanceof Tangible) {
         force.set(force.add(((Tangible)element).force(posEE, velEE)));
      }
   }
  return force;
}
```

**Comment by JRegimbal** [comment]
@rubiarg oops I thought this was in the main branch, but I fixed this as part of d45d7d67228218f39755223d15c58ebdf8f1b008.
